version: "3.8"

services:
  ocrsvc:
    build: ./apis/ocr
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./apis/ocr/:/usr/apps/apis/ocr/
    ports:
      - 8002:8000
